version: "3.7"
services:
  flog:
      image: mingrammer/flog
      container_name: flog
      command: "-f json -l -d 1"
      networks:
        - elk-nginx

  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    container_name: elasticsearch_${ELK_VERSION}
    build:
      context: ./elasticsearch
      args:
        ELK_VERSION: $ELK_VERSION
    mem_limit: 1G
    ports:
      - "9200:9200"
    expose:
      - 9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
    networks:
      - elk-nginx

  kibana:
    image: kibana:${ELK_VERSION}
    container_name: kibana_${ELK_VERSION}
    build:
      context: ./kibana
      args:
        ELK_VERSION: $ELK_VERSION
    mem_limit: 1G
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/data:/usr/share/kibana/data
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - elk-nginx      
      
  logstash:
    image: logstash:${ELK_VERSION}
    container_name: logstash_${ELK_VERSION}
    build:
      context: ./logstash
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - STDOUT=true
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "5044:5044"       # Logstash Beats [filebeat] input
      - "5001:5001/tcp"   # Logstash TCP input
      - "5001:5001/udp"   # Logstash UDP input
      - "9600:9600"       # Logstash monitoring API
    networks:
      - elk-nginx
    labels:
      co.elastic.logs/enabled: "false" # for Filebeat

  filebeat:
    image: filebeat:${ELK_VERSION}
    container_name: filebeat_${ELK_VERSION}
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    entrypoint: filebeat -e -strict.perms=false
    user: root
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch
      - logstash
      - kibana
    networks:
      - elk-nginx
    labels:
      co.elastic.logs/enabled: "false"
      
networks:
  elk-nginx:
    driver: bridge
