ARG ELK_VERSION

FROM docker.elastic.co/beats/filebeat:${ELK_VERSION}

# Home path:    [/usr/share/filebeat]
# Config path:  [/usr/share/filebeat]
# Data path:    [/usr/share/filebeat/data]
# Logs path:    [/usr/share/filebeat/logs]